services:
  - type: web
    name: power-forecast-dashboard
    env: python
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    pythonVersion: "3.11"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
